"""
添加数据生成模块

Revision ID: 0004
Revises: 0003
Create Date: 2026-04-08 08:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建生成模板表
    op.create_table('generationtemplate',
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('generator_name', sa.String(length=50), nullable=False),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('is_preset', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generationtemplate_id'), 'generationtemplate', ['id'], unique=False)
    
    # 创建生成任务表
    op.create_table('generationjob',
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('generator_name', sa.String(length=50), nullable=False),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('progress', sa.Float(), nullable=False),
        sa.Column('processed_count', sa.Integer(), nullable=False),
        sa.Column('total_count', sa.Integer(), nullable=False),
        sa.Column('success_count', sa.Integer(), nullable=False),
        sa.Column('failed_count', sa.Integer(), nullable=False),
        sa.Column('output_dataset_id', sa.String(length=36), nullable=True),
        sa.Column('celery_task_id', sa.String(length=100), nullable=True),
        sa.Column('annotation_format', sa.String(length=10), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('execution_logs', sa.JSON(), nullable=False),
        sa.Column('quality_report', sa.JSON(), nullable=True),
        sa.Column('timing_stats', sa.JSON(), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['output_dataset_id'], ['dataset.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generationjob_id'), 'generationjob', ['id'], unique=False)
    
    # 创建缺陷库缓存表
    op.create_table('defectlibrarycache',
        sa.Column('source_dataset_id', sa.String(length=36), nullable=False),
        sa.Column('color_mode', sa.String(length=20), nullable=False),
        sa.Column('cache_key', sa.String(length=100), nullable=False),
        sa.Column('cache_path', sa.String(length=500), nullable=False),
        sa.Column('defect_count', sa.Integer(), nullable=False),
        sa.Column('cache_size_mb', sa.Float(), nullable=False),
        sa.Column('expires_at', sa.String(length=30), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_dataset_id'], ['dataset.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cache_key')
    )
    op.create_index(op.f('ix_defectlibrarycache_cache_key'), 'defectlibrarycache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_defectlibrarycache_id'), 'defectlibrarycache', ['id'], unique=False)
    
    # 创建生成预览缓存表
    op.create_table('generationpreview',
        sa.Column('generator_name', sa.String(length=50), nullable=False),
        sa.Column('config_hash', sa.String(length=64), nullable=False),
        sa.Column('preview_image_path', sa.String(length=500), nullable=False),
        sa.Column('base_image_path', sa.String(length=500), nullable=True),
        sa.Column('preview_annotations', sa.JSON(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('expires_at', sa.String(length=30), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generationpreview_id'), 'generationpreview', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generationpreview_id'), table_name='generationpreview')
    op.drop_table('generationpreview')
    op.drop_index(op.f('ix_defectlibrarycache_id'), table_name='defectlibrarycache')
    op.drop_index(op.f('ix_defectlibrarycache_cache_key'), table_name='defectlibrarycache')
    op.drop_table('defectlibrarycache')
    op.drop_index(op.f('ix_generationjob_id'), table_name='generationjob')
    op.drop_table('generationjob')
    op.drop_index(op.f('ix_generationtemplate_id'), table_name='generationtemplate')
    op.drop_table('generationtemplate')
    # ### end Alembic commands ###
